#!/bin/sh

case "$1" in

	""|start|restart|stop)
		exit 0
		;;

	info)
        echo "Info: <center><b>HQ WebUI</b></center>"
        echo "Info: <center><br>Aufruf:<br><a href="/addons/hq-webui" target="_blank">http://IP-Adresse-der-CCU/addons/hq-webui</a></center>"
        echo "Info: <center><br>Readme:<br><a href="https://raw.github.com/hobbyquaker/hq-webui/master/README.md" target="_blank">https://raw.github.com/hobbyquaker/hq-webui/master/README.md</a></center>"
        echo "Name: HQ WebUI"
        echo "Version: 1.3.2"
        echo "Operations: uninstall"
        ;;
	uninstall)
		rm -r /usr/local/etc/config/addons/www/hq-webui
		;;
	*)
        echo "Usage: hobbyquaker-webui {info|uninstall}" >&2
        exit 1
        ;;

esac

exit 0
