#!/bin/sh

case "$1" in

	""|start|restart|stop)
		exit 0
		;;

	info)
        echo "Info: <center><b>HQ WebUI</b></center>"
        echo "Info: <center><br>Aufruf:<br><a href="/addons/hq-webui" target="_blank">http://IP-Adresse-der-CCU/addons/hq-webui</a></center>"
        echo "Name: HQ WebUI"
        echo "Version: 1.3"
        echo "Operations: uninstall"
        ;;
	uninstall)
		rm -r /usr/local/etc/config/addons/www/hq-webui
		;;
	*)
        echo "Usage: hobbyquaker-webui {info|uninstall}" >&2
        exit 1
        ;;

esac

exit 0
