#!/bin/sh

# check for unsupported platforms
if grep -qim1 busmatic /www/api/methods/ccu/downloadFirmware.tcl; then
  exit 13
fi

case "$1" in

  ""|start|restart|stop)
    exit 0
    ;;

  info)
    VER=`cat /etc/config/addons/www/hq/VERSION`
    echo "Info: <b>HQ WebUI CCU Addon</b><br>"
    echo "Info: <a href="https://github.com/hobbyquaker/hq-webui">https://github.com/hobbyquaker/hq-webui</a>"
    echo "Name: HQ WebUI"
    echo "Version: $VER"
    echo "Operations: uninstall"
    echo "Config-Url: /addons/hq/ui"
    echo "Update: /addons/hq/ui/update-check.cgi"
  ;;

  uninstall)
    rm -r /usr/local/etc/config/addons/www/hq
  ;;

  *)
    echo "Usage: hobbyquaker-webui {info|uninstall}" >&2
    exit 1
  ;;

esac

exit 0
