#!/bin/sh

case "$1" in

	""|start|restart|stop)
		exit 0
		;;

	info)
        echo "Info: <b>HQ WebUI</b>"
        echo "Info: <br>Aufruf: <a href="/addons/hq/ui" target="_blank">http://CCU/addons/hq/ui</a>"
        echo "Info: <br>Readme: <a href="https://raw.github.com/hobbyquaker/hq-webui/master/README.md" target="_blank">Lies mich!</a>"
        echo "Name: HQ WebUI"
        echo "Version: 2.3.3"
        echo "Operations: uninstall"
        ;;
	uninstall)
		rm -r /usr/local/etc/config/addons/www/hq
		;;
	*)
        echo "Usage: hobbyquaker-webui {info|uninstall}" >&2
        exit 1
        ;;

esac

exit 0
