#!/bin/sh

ADDONNAME=hq
WWWDIR=/usr/local/etc/config/addons/www/$ADDONNAME
RCDDIR=/usr/local/etc/config/rc.d

if [ "$1" == "" ]; then
  echo "CCU1"
  lcdtool "Installing Addon...   "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" == "CCU2" ]; then
  echo "CCU2"
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  mount /usr/local
fi

mkdir -P $WWWDIR
cp -R $ADDONNAME/* $WWWDIR/
chmod 755 $WWWDIR

cp ./hobbyquaker-webui $RCDDIR/
chmod +x $RCDDIR/hobbyquaker-webui

# sync filesystem to make sure all changes are written to disk
sync

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
