#!/bin/sh

mkdir -p /mnt

if ["$1" == ""]; then
    echo "CCU1"
	mount -t yaffs /dev/mtdblock3 /mnt
else
    echo "CCU2"
    mount -t ubifs ubi1:user /mnt
fi

cp -R ./hq /mnt/etc/config/addons/www/
cp ./hobbyquaker-webui /mnt/etc/config/rc.d
chmod +x /mnt/etc/config/rc.d/hobbyquaker-webui

umount /mnt
